image: node:16

include:
  - project: alchemisten/devops
    ref: main
    file: /ci/base.yml

stages:
  - prepare
  - build
  - lint
  - test
  - release

install:
  stage: prepare
  extends: .npm_install

build:
  stage: build
  script:
    - yarn build

lint:
  stage: lint
  script:
    - yarn lint

test:
  stage: test
  script:
    - yarn test

version:
  stage: release
  extends: .semantic_release
