name: Release
"on":
  push:
    branches:
      - main
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          always-auth: true
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN_TECHUSER }}" > ~/.npmrc
      - run: npm ci
      - run: npm run test
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_TECHUSER }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_TECHUSER }}
